### ISSUE TITLE
USER STORY: Twitter timeline feed on Love Running homepage

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/My-First-Agile-Project#13]
As a **user** I can **see all recent tweets on the Love Running homepage** so that **I can see other people's comments and feedback about love running routes**

## Acceptance Criteria:

* Acceptance Criteria 1: #loverunning tweets appear on Love Running homepage
* Acceptaance Criteria 2:#loverunning timeline for previous 1 week
* Acceptance Criteria 3: Ability to click through to #loverunning full twitter feed

## Tasks:

- [ ] Task 1 - Create timeline down side of homepage
- [ ] Task 2 - Publish all tweets which contain #loverunning
- [ ] Task 3 - expire after one week

#12
