### ISSUE TITLE
USER STORY: Hide my identity in the poll response

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/My-First-Agile-Project#5]
In order to **provide anonymous feedback** as a **user**, I can **choose to hide my identity** in the poll response

## Acceptance Criteria:

* Acceptance Criteria 1: The option should be provided as a checkbox
* Acceptaance Criteria 2: The checkbox should be 'checked' by default
* Acceptance Criteria 3: The option should appear next to the submit button
* Acceptance Criteria 4: After submitting the default submission confirmation should be adjusted to include the username

## Tasks:

- [x] Task 1 - Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter.
- [ ] Task 2 - Create a new field in the model to track the username
- [ ] Task 3 - Update the controller function
- [ ] Task 4 - Update the test scripts
- [ ] Task 5 - Test the functionality
