### ISSUE TITLE
USER STORY: Publish a Poll

### ISSUE THREAD

**Issue by quiltingcode** [quiltingcode/My-First-Agile-Project#6]
As a **website administrator** I can **publish a poll** so that **I can collect user feeback on the routes**

## Acceptance Criteria:

* Acceptance Criteria 1: The poll should appear next to the routes schedule
* Acceptaance Criteria 2: The poll has an expiry date, so that as the weather/seasons change, the poll results change.
* Acceptance Criteria 3: Poll summary states, the best route this week is ....

## Tasks:

- [ ] Task 1 - Update the admin module view: the poll design (HTML and CSS) to include data picker.
- [ ] Task 2 - Update the website view: show "Stay tuned a new poll is coming soon"
- [ ] Task 3 - Create a Javascript function to validate the expiry date is at least after three days.
- [ ] Task 4 - Create a job to check expired polls every day at 11:59 PM and hide them
- [ ] Task 5 - Update the controller function
- [ ] Task 6 - Update the test scripts
- [ ] Task 7 - Test the functionality
